/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eczaneotomasyonu;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TOSHIBA
 */
public class hasta_bilgileri extends javax.swing.JFrame {

    /**
     * Creates new form hasta_bilgileri
     */
    public hasta_bilgileri() {
        initComponents();
        cmb_sosyal.addItem("SSK");
        cmb_sosyal.addItem("Bağkur");
        cmb_sosyal.addItem("Emekli");
        cmb_sosyal.addItem("Yok");
        try {
        Class.forName("com.mysql.jdbc.Driver");
           Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/eczane", "root", ""); //Mysql sunucusuna bağlandık
        Statement st = (Statement) con.createStatement();
        try (ResultSet rs = st.executeQuery("Select * from hasta_bilgileri")) { //Veritabanındaki tabloya bağlandık
            int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
            DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
            for(int i = 1;i<=colcount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i)); //Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++)
                        row[i-1] = rs.getObject(i);
                    tm.addRow(row);
                }
            table_bilgi.setModel(tm);
            txt_adi.setText("");
                
            
        }
        con.close();
    } catch (ClassNotFoundException | SQLException hata) {
        Logger.getLogger(hasta_bilgileri.class.getName()).log(Level.SEVERE, null, hata);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_kimlik = new javax.swing.JTextField();
        txt_adi = new javax.swing.JTextField();
        txt_adres1 = new javax.swing.JTextField();
        txt_telno = new javax.swing.JTextField();
        cmb_sosyal = new javax.swing.JComboBox<>();
        kaydet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_bilgi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        guncel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("TC Kimlik No :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 190, 83, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Adı Soyadı :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 240, 77, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Sosyal Güvencesi :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 280, 120, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Adresi :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 330, 60, 16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Telefonu :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 380, 64, 16);

        txt_kimlik.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txt_kimlik);
        txt_kimlik.setBounds(370, 180, 132, 30);
        getContentPane().add(txt_adi);
        txt_adi.setBounds(370, 230, 132, 30);
        getContentPane().add(txt_adres1);
        txt_adres1.setBounds(370, 320, 132, 30);
        getContentPane().add(txt_telno);
        txt_telno.setBounds(370, 370, 132, 30);

        getContentPane().add(cmb_sosyal);
        cmb_sosyal.setBounds(370, 280, 80, 22);

        kaydet.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kaydet.setText("KAYDET");
        kaydet.setMaximumSize(new java.awt.Dimension(81, 25));
        kaydet.setMinimumSize(new java.awt.Dimension(81, 25));
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });
        getContentPane().add(kaydet);
        kaydet.setBounds(150, 480, 140, 30);

        table_bilgi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_bilgi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_bilgiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_bilgi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 830, 120);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("SİL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 480, 140, 30);

        guncel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        guncel.setText("GÜNCELLE");
        guncel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelActionPerformed(evt);
            }
        });
        getContentPane().add(guncel);
        guncel.setBounds(320, 480, 140, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\javatasarim\\background.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
        try {
           String tc_kimlik1=txt_kimlik.getText();
            String adi_soyadi1=txt_adi.getText();
            String guvence1= String.valueOf(cmb_sosyal.getSelectedItem());
            String adres1=txt_adres1.getText();
            String tel_no1=txt_telno.getText();
            
            if (tc_kimlik1.equals("") || adi_soyadi1.equals("") || adres1.equals("")|| tel_no1.equals("")){

                JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");

            } else {            
                Class.forName("com.mysql.jdbc.Driver");

                java.sql.Connection con = null;
                java.sql.Statement st = null;
                ResultSet rs = null;

                con = DriverManager.getConnection("jdbc:mysql://localhost/eczane","root","");
                
                st =(java.sql.Statement) con.createStatement();

                String sql = "INSERT INTO hasta_bilgileri (tc_kimlik,adi_soyadi,guvence,adres,tel_no)" 
                        + " VALUES ('"+tc_kimlik1+"','"+adi_soyadi1+"', '"+guvence1+"', '"+adres1+"','"+tel_no1+"')";

                st.executeUpdate(sql); //
                JOptionPane.showMessageDialog(null," Hasta Bilgisi Eklenmiştir.");
       }
       }
       catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
        try {
        Class.forName("com.mysql.jdbc.Driver");
           Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/eczane", "root", ""); //Mysql sunucusuna bağlandık
        Statement st = (Statement) con.createStatement();
        try (ResultSet rs = st.executeQuery("Select * from hasta_bilgileri")) { //Veritabanındaki tabloya bağlandık
            int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
            DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
            for(int i = 1;i<=colcount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i)); //Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++)
                        row[i-1] = rs.getObject(i);
                    tm.addRow(row);
                }
            table_bilgi.setModel(tm);
           
                
            
        }
        con.close();
    } catch (ClassNotFoundException | SQLException hata) {
        Logger.getLogger(hasta_bilgileri.class.getName()).log(Level.SEVERE, null, hata);
    }
        
    }//GEN-LAST:event_kaydetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

try {
        Class.forName("com.mysql.jdbc.Driver");
           java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/eczane","root",""); //Mysql sunucusuna bağlandık
        java.sql.Statement st = (java.sql.Statement) con.createStatement();
        try (ResultSet rs = st.executeQuery("Select * from hasta_bilgileri")) { //Veritabanındaki tabloya bağlandık
            int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
            DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
            for(int i = 1;i<=colcount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i)); //Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++)
                        row[i-1] = rs.getObject(i);
                    tm.addRow(row);
                }
            table_bilgi.setModel(tm);
        }
        
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(ilac_bilgi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ilac_bilgi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try{
           
            String kimlik=txt_kimlik.getText();
            
            
             Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
                Statement st = null;
                ResultSet rs = null;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/eczane","root","");
                st =(Statement) con.createStatement();
                String sql="DELETE FROM `hasta_bilgileri` WHERE tc_kimlik='"+kimlik+"'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Hasta Bilgisi Silinmiştir");
                txt_adi.setText("");
                txt_kimlik.setText("");
                txt_adres1.setText("");
                txt_telno.setText("");
                
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(hasta_bilgileri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(hasta_bilgileri.class.getName()).log(Level.SEVERE, null, ex);
           
        }
        
        try {
        Class.forName("com.mysql.jdbc.Driver");
        try (Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/eczane", "root", "") //Mysql sunucusuna bağlandık
                ) {     Statement st = (Statement) con.createStatement();
                try (ResultSet rs = st.executeQuery("Select * from hasta_bilgileri")) { //Veritabanındaki tabloya bağlandık
                    int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
                    DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
                    for(int i = 1;i<=colcount;i++)
                        tm.addColumn(rs.getMetaData().getColumnName(i)); //Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
                    while(rs.next())
                    {
                        Object[] row = new Object[colcount];
                        for(int i=1;i<=colcount;i++)
                            row[i-1] = rs.getObject(i);
                        tm.addRow(row);
                    }
                    table_bilgi.setModel(tm);
                    
                    
                    
                }
           
                
            
        }
    } catch (ClassNotFoundException | SQLException hata) {
        Logger.getLogger(hasta_bilgileri.class.getName()).log(Level.SEVERE, null, hata);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void table_bilgiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_bilgiMouseClicked
        String tc_kimlik = table_bilgi.getValueAt(table_bilgi.getSelectedRow(), 1).toString();
        String adi = table_bilgi.getValueAt(table_bilgi.getSelectedRow(), 2).toString();
        String adres1 = table_bilgi.getValueAt(table_bilgi.getSelectedRow(), 4).toString();
        String telno1 = table_bilgi.getValueAt(table_bilgi.getSelectedRow(), 5).toString();
        
        txt_adi.setText(adi);
        txt_kimlik.setText(tc_kimlik);
        txt_adres1.setText(adres1);
        txt_telno.setText(telno1);
        
    }//GEN-LAST:event_table_bilgiMouseClicked

    private void guncelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelActionPerformed
        try{
            String kimlik=txt_kimlik.getText();
            String adi=txt_adi.getText();
            String sos=String.valueOf(cmb_sosyal.getSelectedItem());
            String adres=txt_adres1.getText();
            String telno1=txt_telno.getText();
           
           
             Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
                Statement st = null;
                ResultSet rs = null;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/eczane","root","");
                st =(Statement) con.createStatement();
                String sql="UPDATE `hasta_bilgileri` SET tc_kimlik='"+kimlik+"', adi_soyadi='"+adi+"', guvence='"+sos+"', adres='"+adres+"', tel_no='"+telno1+"' WHERE tc_kimlik='"+kimlik+"'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null," Hasta Bilgisi Güncellenmiştir.");
                txt_adi.setText("");
                txt_kimlik.setText("");
                txt_adres1.setText("");
                txt_telno.setText("");
                
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(hasta_bilgileri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(hasta_bilgileri.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
        Class.forName("com.mysql.jdbc.Driver");
           Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/eczane", "root", ""); //Mysql sunucusuna bağlandık
        Statement st = (Statement) con.createStatement();
        try (ResultSet rs = st.executeQuery("Select * from hasta_bilgileri")) { //Veritabanındaki tabloya bağlandık
            int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
            DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
            for(int i = 1;i<=colcount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i)); //Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++)
                        row[i-1] = rs.getObject(i);
                    tm.addRow(row);
                }
            table_bilgi.setModel(tm);
            txt_adi.setText("");
                
            
        }
        con.close();
    } catch (ClassNotFoundException | SQLException hata) {
        Logger.getLogger(hasta_bilgileri.class.getName()).log(Level.SEVERE, null, hata);
    }
    }//GEN-LAST:event_guncelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hasta_bilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hasta_bilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hasta_bilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hasta_bilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hasta_bilgileri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_sosyal;
    private javax.swing.JButton guncel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kaydet;
    private javax.swing.JTable table_bilgi;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextField txt_adres1;
    private javax.swing.JTextField txt_kimlik;
    private javax.swing.JTextField txt_telno;
    // End of variables declaration//GEN-END:variables
}
