/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eczaneotomasyonu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TOSHIBA
 */
public class ilac_bilgi extends javax.swing.JFrame {

    /**
     * Creates new form ilac_bilgi
     */
    public ilac_bilgi() {
        initComponents();
        try {
        Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/eczane","root",""); //Mysql sunucusuna bağlandık
        Statement st = (Statement) con.createStatement();
        try (ResultSet rs = st.executeQuery("Select * from ilac_bilgileri")) { //Veritabanındaki tabloya bağlandık
            int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
            DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
            for(int i = 1;i<=colcount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i)); //Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++)
                        row[i-1] = rs.getObject(i);
                    tm.addRow(row);
                }
            table_bilgi.setModel(tm);
        }
        
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(ilac_bilgi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ilac_bilgi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_bilgi = new javax.swing.JTable();
        txt_adi = new javax.swing.JTextField();
        txt_firma = new javax.swing.JTextField();
        txt_kutu = new javax.swing.JTextField();
        txt_fiyat = new javax.swing.JTextField();
        txt_amac = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("İlaç Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 310, 115, 33);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("İlaç Güncelle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 310, 115, 33);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("İlaç Sil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 310, 115, 33);

        table_bilgi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_bilgi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_bilgiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_bilgi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 800, 98);
        getContentPane().add(txt_adi);
        txt_adi.setBounds(139, 116, 130, 32);
        getContentPane().add(txt_firma);
        txt_firma.setBounds(139, 155, 130, 32);
        getContentPane().add(txt_kutu);
        txt_kutu.setBounds(139, 200, 130, 32);
        getContentPane().add(txt_fiyat);
        txt_fiyat.setBounds(467, 116, 130, 32);

        txt_amac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amacActionPerformed(evt);
            }
        });
        getContentPane().add(txt_amac);
        txt_amac.setBounds(467, 161, 130, 32);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("İlaç Adı :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(64, 124, 57, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Üretici Firma :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(33, 163, 88, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Kutu Sayısı :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(41, 208, 80, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("İlaç Fiyatı :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 124, 70, 16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Kullanım Amacı :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(336, 169, 104, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\javatasarim\\background.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try{
           
            String ilac=txt_adi.getText();
            
            
             Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
                Statement st = null;
                ResultSet rs = null;
                con = DriverManager.getConnection("jdbc:mysql://localhost/eczane","root","");
                st =(Statement) con.createStatement();
                String sql="DELETE FROM `ilac_bilgileri` WHERE ilac_adi='"+ilac+"'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"İlaç Bilgisi Silinmiştir");
                txt_adi.setText("");
                txt_firma.setText("");
                txt_fiyat.setText("");
                
                txt_kutu.setText("");
                txt_amac.setText("");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ilac_bilgi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ilac_bilgi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
        Class.forName("com.mysql.jdbc.Driver");
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost/eczane","root","") //Mysql sunucusuna bağlandık
                ) {             Statement st = (Statement) con.createStatement();
                try (ResultSet rs = st.executeQuery("Select * from ilac_bilgileri")) { //Veritabanındaki tabloya bağlandık
                    int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
                    DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
                    for(int i = 1;i<=colcount;i++)
                        tm.addColumn(rs.getMetaData().getColumnName(i)); //Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
                    while(rs.next())
                    {
                        Object[] row = new Object[colcount];
                        for(int i=1;i<=colcount;i++)
                            row[i-1] = rs.getObject(i);
                        tm.addRow(row);
                    }
                    table_bilgi.setModel(tm);
                }
        }
        } catch (SQLException ex) {
            Logger.getLogger(ilac_bilgi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ilac_bilgi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
           String ilac_adi=txt_adi.getText();
            String firma=txt_firma.getText();
            String kutu=txt_kutu.getText();
            String fiyat=txt_fiyat.getText();
            String amac=txt_amac.getText();
            if (ilac_adi.equals("") || firma.equals("") || kutu.equals("")|| fiyat.equals("") || amac.equals("")){

                JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");

            } else {            
                Class.forName("com.mysql.jdbc.Driver");

                Connection con = null;
                Statement st = null;
                ResultSet rs = null;

                con = DriverManager.getConnection("jdbc:mysql://localhost/eczane","root","");
                
                st =(Statement) con.createStatement();

                String sql = "INSERT INTO ilac_bilgileri (ilac_adi,uretici_firma,kutu_sayisi,fiyati,kullanim_amaci)" 
                        + " VALUES ('"+ilac_adi+"','"+firma+"', '"+kutu+"', '"+fiyat+"','"+amac+"')";

                st.executeUpdate(sql); //
                JOptionPane.showMessageDialog(null," İlaç Bilgisi Eklenmiştir.");
       }
       }
       catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
       
       try {
        Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/eczane","root",""); //Mysql sunucusuna bağlandık
        Statement st = (Statement) con.createStatement();
        try (ResultSet rs = st.executeQuery("Select * from ilac_bilgileri")) { //Veritabanındaki tabloya bağlandık
            int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
            DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
            for(int i = 1;i<=colcount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i)); //Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++)
                        row[i-1] = rs.getObject(i);
                    tm.addRow(row);
                }
            table_bilgi.setModel(tm);
        }
        
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(ilac_bilgi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ilac_bilgi.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_amacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_amacActionPerformed

    private void table_bilgiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_bilgiMouseClicked
        String ilac_adi = table_bilgi.getValueAt(table_bilgi.getSelectedRow(), 1).toString();
        String firma = table_bilgi.getValueAt(table_bilgi.getSelectedRow(), 2).toString();
        String kutu = table_bilgi.getValueAt(table_bilgi.getSelectedRow(), 3).toString();
        String fiyat = table_bilgi.getValueAt(table_bilgi.getSelectedRow(), 4).toString();
        String amac = table_bilgi.getValueAt(table_bilgi.getSelectedRow(), 5).toString();
        txt_adi.setText(ilac_adi);
        txt_firma.setText(firma);
        txt_kutu.setText(kutu);
        txt_fiyat.setText(fiyat);
        txt_amac.setText(amac);
    }//GEN-LAST:event_table_bilgiMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        

         try{
            String ilac=txt_adi.getText();
            String firma=txt_firma.getText();
            String kutu=txt_kutu.getText();
            String fiyati=txt_fiyat.getText();
            String amac=txt_amac.getText();
           
           
             Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection con = null;
                com.mysql.jdbc.Statement st = null;
                ResultSet rs = null;
                con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/eczane","root","");
                st =(com.mysql.jdbc.Statement) con.createStatement();
                String sql="UPDATE `ilac_bilgileri` SET ilac_adi='"+ilac+"', uretici_firma='"+firma+"', kutu_sayisi='"+kutu+"', fiyati='"+fiyati+"', kullanim_amaci='"+amac+"' WHERE ilac_adi='"+ilac+"'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"İlaç Bilgisi Güncellenmiştir.");
                txt_adi.setText("");
                txt_kutu.setText("");
                txt_amac.setText("");
                txt_firma.setText("");
                txt_fiyat.setText("");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ilac_bilgileri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ilac_bilgileri.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
        Class.forName("com.mysql.jdbc.Driver");
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost/eczane","root","") //Mysql sunucusuna bağlandık
                ) {             Statement st = (Statement) con.createStatement();
                try (ResultSet rs = st.executeQuery("Select * from ilac_bilgileri")) { //Veritabanındaki tabloya bağlandık
                    int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
                    DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
                    for(int i = 1;i<=colcount;i++)
                        tm.addColumn(rs.getMetaData().getColumnName(i)); //Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
                    while(rs.next())
                    {
                        Object[] row = new Object[colcount];
                        for(int i=1;i<=colcount;i++)
                            row[i-1] = rs.getObject(i);
                        tm.addRow(row);
                    }
                    table_bilgi.setModel(tm);
                }
        }
        } catch (SQLException ex) {
            Logger.getLogger(ilac_bilgi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ilac_bilgi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ilac_bilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ilac_bilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ilac_bilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ilac_bilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ilac_bilgi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_bilgi;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextField txt_amac;
    private javax.swing.JTextField txt_firma;
    private javax.swing.JTextField txt_fiyat;
    private javax.swing.JTextField txt_kutu;
    // End of variables declaration//GEN-END:variables

    void setWisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class ilac_bilgileri {

        public ilac_bilgileri() {
        }
    }
}
