/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eczaneotomasyonu;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author TOSHIBA
 */
public class kayitol extends javax.swing.JFrame {

    /**
     * Creates new form kayitol
     */
    public kayitol() {
        initComponents();
        cmb_turu.addItem("Yönetici");
        cmb_turu.addItem("Personel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_kadi = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_sifre = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmb_turu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);
        getContentPane().add(txt_kadi);
        txt_kadi.setBounds(200, 200, 140, 30);
        getContentPane().add(txt_mail);
        txt_mail.setBounds(200, 280, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Kullanıcı Adı:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 210, 100, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Şifre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 250, 50, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("E-Posta:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 290, 60, 16);
        getContentPane().add(txt_sifre);
        txt_sifre.setBounds(200, 240, 140, 30);

        jButton1.setBackground(new java.awt.Color(110, 221, 227));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Kayıt Ol");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 340, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Kullanıcı Türü:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 160, 89, 16);

        getContentPane().add(cmb_turu);
        cmb_turu.setBounds(200, 150, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Kayıt olmak için boşlukları doldurun ve kayıt ol butonuna basınız..");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 40, 590, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\javatasarim\\background.png")); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        String kadi=txt_kadi.getText();
        String sifre=txt_sifre.getText();
        String email=txt_mail.getText();
        String turu=String.valueOf(cmb_turu.getSelectedItem());
        
            if (kadi.equals("")   ||   sifre.equals("")   ||   email.equals(""))
            
        {
            JOptionPane.showMessageDialog(this,"Lütfen Boş Alanları Doldurunuz.");
            
        }else{
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;
            
            con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/eczane","root","");
            
            st=(Statement)con.createStatement();
          
            
           String sql="INSERT INTO uyeler (turu,kadi,sifre,email)" + " VALUES ('"+turu+"','"+kadi+"','"+sifre+"','"+email+"')";
            
            st.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(null,kadi + " İsimli kullanıcı eklenmiştir.");
            
        }
        }catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());
            
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(this,"Veri Tabanına Bağlanılamadı !" + ex.toString());
            
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayitol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayitol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayitol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayitol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kayitol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_turu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_kadi;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JPasswordField txt_sifre;
    // End of variables declaration//GEN-END:variables
}
